export const currencyNames = {
  USD: 'United States Dollar',
  UGX: 'Ugandan Shilling',
  AED: 'United Arab Emirates Dirham',
  AFN: 'Afghan Afghani',
  ALL: 'Albanian Lek',
  AMD: 'Armenian Dram',
  ANG: 'Netherlands Antillean Guilder',
  AOA: 'Angolan Kwanza',
  ARS: 'Argentine Peso',
  AUD: 'Australian Dollar',
  AWG: 'Aruban Florin',
  AZN: 'Azerbaijani Manat',
  BAM: 'Bosnia-Herzegovina Convertible Mark',
  BBD: 'Barbadian Dollar',
  BDT: 'Bangladeshi Taka',
  BGN: 'Bulgarian Lev',
  BHD: 'Bahraini Dinar',
  BIF: 'Burundian Franc',
  BMD: 'Bermudan Dollar',
  BND: 'Brunei Dollar',
  BOB: 'Bolivian Boliviano',
  BRL: 'Brazilian Real',
  BSD: 'Bahamian Dollar',
  BTC: 'Bitcoin',
  BTN: 'Bhutanese Ngultrum',
  BWP: 'Botswanan Pula',
  BYN: 'Belarusian Ruble',
  BZD: 'Belize Dollar',
  CAD: 'Canadian Dollar',
  CDF: 'Congolese Franc',
  CHF: 'Swiss Franc',
  CLF: 'Chilean Unit of Account (UF)',
  CLP: 'Chilean Peso',
  CNH: 'Chinese Yuan (Offshore)',
  CNY: 'Chinese Yuan',
  COP: 'Colombian Peso',
  CRC: 'Costa Rican Colón',
  CUC: 'Cuban Convertible Peso',
  CUP: 'Cuban Peso',
  CVE: 'Cape Verdean Escudo',
  CZK: 'Czech Republic Koruna',
  DJF: 'Djiboutian Franc',
  DKK: 'Danish Krone',
  DOP: 'Dominican Peso',
  DZD: 'Algerian Dinar',
  EGP: 'Egyptian Pound',
  ERN: 'Eritrean Nakfa',
  ETB: 'Ethiopian Birr',
  EUR: 'Euro',
  FJD: 'Fijian Dollar',
  FKP: 'Falkland Islands Pound',
  GBP: 'British Pound Sterling',
  GEL: 'Georgian Lari',
  GGP: 'Guernsey Pound',
  GHS: 'Ghanaian Cedi',
  GIP: 'Gibraltar Pound',
  GMD: 'Gambian Dalasi',
  GNF: 'Guinean Franc',
  GTQ: 'Guatemalan Quetzal',
  GYD: 'Guyanaese Dollar',
  HKD: 'Hong Kong Dollar',
  HNL: 'Honduran Lempira',
  HRK: 'Croatian Kuna',
  HTG: 'Haitian Gourde',
  HUF: 'Hungarian Forint',
  IDR: 'Indonesian Rupiah',
  ILS: 'Israeli New Sheqel',
  IMP: 'Manx pound',
  INR: 'Indian Rupee',
  IQD: 'Iraqi Dinar',
  IRR: 'Iranian Rial',
  ISK: 'Icelandic Króna',
  JEP: 'Jersey Pound',
  JMD: 'Jamaican Dollar',
  JOD: 'Jordanian Dinar',
  JPY: 'Japanese Yen',
  KES: 'Kenyan Shilling',
  KGS: 'Kyrgystani Som',
  KHR: 'Cambodian Riel',
  KMF: 'Comorian Franc',
  KPW: 'North Korean Won',
  KRW: 'South Korean Won',
  KWD: 'Kuwaiti Dinar',
  KYD: 'Cayman Islands Dollar',
  KZT: 'Kazakhstani Tenge',
  LAK: 'Laotian Kip',
  LBP: 'Lebanese Pound',
  LKR: 'Sri Lankan Rupee',
  LRD: 'Liberian Dollar',
  LSL: 'Lesotho Loti',
  LYD: 'Libyan Dinar',
  MAD: 'Moroccan Dirham',
  MDL: 'Moldovan Leu',
  MGA: 'Malagasy Ariary',
  MKD: 'Macedonian Denar',
  MMK: 'Myanma Kyat',
  MNT: 'Mongolian Tugrik',
  MOP: 'Macanese Pataca',
  MRU: 'Mauritanian Ouguiya',
  MUR: 'Mauritian Rupee',
  MVR: 'Maldivian Rufiyaa',
  MWK: 'Malawian Kwacha',
  MXN: 'Mexican Peso',
  MYR: 'Malaysian Ringgit',
  MZN: 'Mozambican Metical',
  NAD: 'Namibian Dollar',
  NGN: 'Nigerian Naira',
  NIO: 'Nicaraguan Córdoba',
  NOK: 'Norwegian Krone',
  NPR: 'Nepalese Rupee',
  NZD: 'New Zealand Dollar',
  OMR: 'Omani Rial',
  PAB: 'Panamanian Balboa',
  PEN: 'Peruvian Nuevo Sol',
  PGK: 'Papua New Guinean Kina',
  PHP: 'Philippine Peso',
  PKR: 'Pakistani Rupee',
  PLN: 'Polish Zloty',
  PYG: 'Paraguayan Guarani',
  QAR: 'Qatari Rial',
  RON: 'Romanian Leu',
  RSD: 'Serbian Dinar',
  RUB: 'Russian Ruble',
  RWF: 'Rwandan Franc',
  SAR: 'Saudi Riyal',
  SBD: 'Solomon Islands Dollar',
  SCR: 'Seychellois Rupee',
  SDG: 'Sudanese Pound',
  SEK: 'Swedish Krona',
  SGD: 'Singapore Dollar',
  SHP: 'Saint Helena Pound',
  SLL: 'Sierra Leonean Leone',
  SOS: 'Somali Shilling',
  SRD: 'Surinamese Dollar',
  SSP: 'South Sudanese Pound',
  STD: 'São Tomé and Príncipe Dobra (pre-2018)',
  STN: 'São Tomé and Príncipe Dobra',
  SVC: 'Salvadoran Colón',
  SYP: 'Syrian Pound',
  SZL: 'Swazi Lilangeni',
  THB: 'Thai Baht',
  TJS: 'Tajikistani Somoni',
  TMT: 'Turkmenistani Manat',
  TND: 'Tunisian Dinar',
  TOP: "Tongan Pa'anga",
  TRY: 'Turkish Lira',
  TTD: 'Trinidad and Tobago Dollar',
  TWD: 'New Taiwan Dollar',
  TZS: 'Tanzanian Shilling',
  UAH: 'Ukrainian Hryvnia',
  UYU: 'Uruguayan Peso',
  UZS: 'Uzbekistan Som',
  VEF: 'Venezuelan Bolívar Fuerte (Old)',
  VES: 'Venezuelan Bolívar Soberano',
  VND: 'Vietnamese Dong',
  VUV: 'Vanuatu Vatu',
  WST: 'Samoan Tala',
  XAF: 'CFA Franc BEAC',
  XAG: 'Silver Ounce',
  XAU: 'Gold Ounce',
  XCD: 'East Caribbean Dollar',
  XDR: 'Special Drawing Rights',
  XOF: 'CFA Franc BCEAO',
  XPD: 'Palladium Ounce',
  XPF: 'CFP Franc',
  XPT: 'Platinum Ounce',
  YER: 'Yemeni Rial',
  ZAR: 'South African Rand',
  ZMW: 'Zambian Kwacha',
  ZWL: 'Zimbabwean Dollar',
};

export const currencySymbols = {
  AED: 'د.إ',
  AFN: '؋',
  ALL: 'L',
  AMD: '֏',
  ANG: 'ƒ',
  AOA: 'Kz',
  ARS: '$',
  AUD: '$',
  AWG: 'ƒ',
  AZN: '₼',
  BAM: 'KM',
  BBD: '$',
  BDT: '৳',
  BGN: 'лв',
  BHD: '.د.ب',
  BIF: 'FBu',
  BMD: '$',
  BND: '$',
  BOB: '$b',
  BRL: 'R$',
  BSD: '$',
  BTC: '฿',
  BTN: 'Nu.',
  BWP: 'P',
  BYR: 'p.',
  BZD: 'BZ$',
  CAD: '$',
  CDF: 'FC',
  CHF: 'CHF',
  CLP: '$',
  CNY: '¥',
  COP: '$',
  CRC: '₡',
  CUC: '$',
  CUP: '₱',
  CVE: '$',
  CZK: 'Kč',
  DJF: 'Fdj',
  DKK: 'kr',
  DOP: 'RD$',
  DZD: 'دج',
  EEK: 'kr',
  EGP: '£',
  ERN: 'Nfk',
  ETB: 'Br',
  ETH: 'Ξ',
  EUR: '€',
  FJD: '$',
  FKP: '£',
  GBP: '£',
  GEL: '₾',
  GGP: '£',
  GHC: '₵',
  GHS: 'GH₵',
  GIP: '£',
  GMD: 'D',
  GNF: 'FG',
  GTQ: 'Q',
  GYD: '$',
  HKD: '$',
  HNL: 'L',
  HRK: 'kn',
  HTG: 'G',
  HUF: 'Ft',
  IDR: 'Rp',
  ILS: '₪',
  IMP: '£',
  INR: '₹',
  IQD: 'ع.د',
  IRR: '﷼',
  ISK: 'kr',
  JEP: '£',
  JMD: 'J$',
  JOD: 'JD',
  JPY: '¥',
  KES: 'KSh',
  KGS: 'лв',
  KHR: '៛',
  KMF: 'CF',
  KPW: '₩',
  KRW: '₩',
  KWD: 'KD',
  KYD: '$',
  KZT: 'лв',
  LAK: '₭',
  LBP: '£',
  LKR: '₨',
  LRD: '$',
  LSL: 'M',
  LTC: 'Ł',
  LTL: 'Lt',
  LVL: 'Ls',
  LYD: 'LD',
  MAD: 'MAD',
  MDL: 'lei',
  MGA: 'Ar',
  MKD: 'ден',
  MMK: 'K',
  MNT: '₮',
  MOP: 'MOP$',
  MRO: 'UM',
  MUR: '₨',
  MVR: 'Rf',
  MWK: 'MK',
  MXN: '$',
  MYR: 'RM',
  MZN: 'MT',
  NAD: '$',
  NGN: '₦',
  NIO: 'C$',
  NOK: 'kr',
  NPR: '₨',
  NZD: '$',
  OMR: '﷼',
  PAB: 'B/.',
  PEN: 'S/.',
  PGK: 'K',
  PHP: '₱',
  PKR: '₨',
  PLN: 'zł',
  PYG: 'Gs',
  QAR: '﷼',
  RMB: '￥',
  RON: 'lei',
  RSD: 'Дин.',
  RUB: '₽',
  RWF: 'R₣',
  SAR: '﷼',
  SBD: '$',
  SCR: '₨',
  SDG: 'ج.س.',
  SEK: 'kr',
  SGD: '$',
  SHP: '£',
  SLL: 'Le',
  SOS: 'S',
  SRD: '$',
  SSP: '£',
  STD: 'Db',
  SVC: '$',
  SYP: '£',
  SZL: 'E',
  THB: '฿',
  TJS: 'SM',
  TMT: 'T',
  TND: 'د.ت',
  TOP: 'T$',
  TRL: '₤',
  TRY: '₺',
  TTD: 'TT$',
  TVD: '$',
  TWD: 'NT$',
  TZS: 'TSh',
  UAH: '₴',
  UGX: 'USh',
  USD: '$',
  UYU: '$U',
  UZS: 'лв',
  VEF: 'Bs',
  VND: '₫',
  VUV: 'VT',
  WST: 'WS$',
  XAF: 'FCFA',
  XBT: 'Ƀ',
  XCD: '$',
  XOF: 'CFA',
  XPF: '₣',
  YER: '﷼',
  ZAR: 'R',
  ZWD: 'Z$',
};

export const countryCodes = [
  {
    name: 'Afghanistan',
    callingCode: '93',
  },
  {
    name: 'Albania',
    callingCode: '355',
  },
  {
    name: 'Algeria',
    callingCode: '213',
  },
  {
    name: 'American Samoa',
    callingCode: '1684',
  },
  {
    name: 'Andorra',
    callingCode: '376',
  },
  {
    name: 'Angola',
    callingCode: '244',
  },
  {
    name: 'Anguilla',
    callingCode: '1264',
  },
  {
    name: 'Antarctica',
    callingCode: 672,
  },
  {
    name: 'Antigua and Barbuda',
    callingCode: '1268',
  },
  {
    name: 'Argentina',
    callingCode: '54',
  },
  {
    name: 'Armenia',
    callingCode: '374',
  },
  {
    name: 'Aruba',
    callingCode: '297',
  },
  {
    name: 'Australia',
    callingCode: '61',
  },
  {
    name: 'Austria',
    callingCode: '43',
  },
  {
    name: 'Azerbaijan',
    callingCode: '994',
  },
  {
    name: 'Bahamas',
    callingCode: '1242',
  },
  {
    name: 'Bahrain',
    callingCode: '973',
  },
  {
    name: 'Bangladesh',
    callingCode: '880',
  },
  {
    name: 'Barbados',
    callingCode: '1246',
  },
  {
    name: 'Belarus',
    callingCode: '375',
  },
  {
    name: 'Belgium',
    callingCode: '32',
  },
  {
    name: 'Belize',
    callingCode: '501',
  },
  {
    name: 'Benin',
    callingCode: '229',
  },
  {
    name: 'Bermuda',
    callingCode: '1441',
  },
  {
    name: 'Bhutan',
    callingCode: '975',
  },
  {
    name: 'Bolivia',
    callingCode: '591',
  },
  {
    name: 'Bosnia and Herzegovina',
    callingCode: '387',
  },
  {
    name: 'Botswana',
    callingCode: '267',
  },
  {
    name: 'Bouvet Island',
    callingCode: 55,
  },
  {
    name: 'Brazil',
    callingCode: '55',
  },
  {
    name: 'British Indian Ocean Territory',
    callingCode: '246',
  },
  {
    name: 'Brunei',
    callingCode: '673',
  },
  {
    name: 'Bulgaria',
    callingCode: '359',
  },
  {
    name: 'Burkina Faso',
    callingCode: '226',
  },
  {
    name: 'Burundi',
    callingCode: '257',
  },
  {
    name: 'Cambodia',
    callingCode: '855',
  },
  {
    name: 'Cameroon',
    callingCode: '237',
  },
  {
    name: 'Canada',
    callingCode: '1',
  },
  {
    name: 'Cape Verde',
    callingCode: '238',
  },
  {
    name: 'Cayman Islands',
    callingCode: '1345',
  },
  {
    name: 'Central African Republic',
    callingCode: '236',
  },
  {
    name: 'Chad',
    callingCode: '235',
  },
  {
    name: 'Chile',
    callingCode: '56',
  },
  {
    name: 'China',
    callingCode: '86',
  },
  {
    name: 'Christmas Island',
    callingCode: '61',
  },
  {
    name: 'Cocos (Keeling) Islands',
    callingCode: '61',
  },
  {
    name: 'Colombia',
    callingCode: '57',
  },
  {
    name: 'Comoros',
    callingCode: '269',
  },
  {
    name: 'Congo',
    callingCode: '242',
  },
  {
    name: 'Cook Islands',
    callingCode: '682',
  },
  {
    name: 'Costa Rica',
    callingCode: '506',
  },
  {
    name: 'Croatia',
    callingCode: '385',
  },
  {
    name: 'Cuba',
    callingCode: '53',
  },
  {
    name: 'Cyprus',
    callingCode: '357',
  },
  {
    name: 'Czech Republic',
    callingCode: '420',
  },
  {
    name: 'Denmark',
    callingCode: '45',
  },
  {
    name: 'Djibouti',
    callingCode: '253',
  },
  {
    name: 'Dominica',
    callingCode: '1767',
  },
  {
    name: 'Dominican Republic',
    callingCode: '1849',
  },
  {
    name: 'East Timor',
    callingCode: '670',
  },
  {
    name: 'Ecuador',
    callingCode: '593',
  },
  {
    name: 'Egypt',
    callingCode: '20',
  },
  {
    name: 'El Salvador',
    callingCode: '503',
  },
  {
    name: 'England',
    callingCode: '44',
  },
  {
    name: 'Equatorial Guinea',
    callingCode: '240',
  },
  {
    name: 'Eritrea',
    callingCode: '291',
  },
  {
    name: 'Estonia',
    callingCode: '372',
  },
  {
    name: 'Ethiopia',
    callingCode: '251',
  },
  {
    name: 'Falkland Islands',
    callingCode: '500',
  },
  {
    name: 'Faroe Islands',
    callingCode: '298',
  },
  {
    name: 'Fiji Islands',
    callingCode: '679',
  },
  {
    name: 'Finland',
    callingCode: '358',
  },
  {
    name: 'France',
    callingCode: '33',
  },
  {
    name: 'French Guiana',
    callingCode: '594',
  },
  {
    name: 'French Polynesia',
    callingCode: '689',
  },
  {
    name: 'French Southern territories',
    callingCode: '262',
  },
  {
    name: 'Gabon',
    callingCode: '241',
  },
  {
    name: 'Gambia',
    callingCode: '220',
  },
  {
    name: 'Georgia',
    callingCode: '995',
  },
  {
    name: 'Germany',
    callingCode: '49',
  },
  {
    name: 'Ghana',
    callingCode: '233',
  },
  {
    name: 'Gibraltar',
    callingCode: '350',
  },
  {
    name: 'Greece',
    callingCode: '30',
  },
  {
    name: 'Greenland',
    callingCode: '299',
  },
  {
    name: 'Grenada',
    callingCode: '1473',
  },
  {
    name: 'Guadeloupe',
    callingCode: '590',
  },
  {
    name: 'Guam',
    callingCode: '1671',
  },
  {
    name: 'Guatemala',
    callingCode: '502',
  },
  {
    name: 'Guinea',
    callingCode: '224',
  },
  {
    name: 'Guinea-Bissau',
    callingCode: '245',
  },
  {
    name: 'Guyana',
    callingCode: '592',
  },
  {
    name: 'Haiti',
    callingCode: '509',
  },
  {
    name: 'Heard Island and McDonald Islands',
    callingCode: '0',
  },
  {
    name: 'Holy See (Vatican City State)',
    callingCode: '379',
  },
  {
    name: 'Honduras',
    callingCode: '504',
  },
  {
    name: 'Hong Kong',
    callingCode: '852',
  },
  {
    name: 'Hungary',
    callingCode: '36',
  },
  {
    name: 'Iceland',
    callingCode: '354',
  },
  {
    name: 'India',
    callingCode: '91',
  },
  {
    name: 'Indonesia',
    callingCode: '62',
  },
  {
    name: 'Iran',
    callingCode: '98',
  },
  {
    name: 'Iraq',
    callingCode: '964',
  },
  {
    name: 'Ireland',
    callingCode: '353',
  },
  {
    name: 'Israel',
    callingCode: '972',
  },
  {
    name: 'Italy',
    callingCode: '39',
  },
  {
    name: 'Ivory Coast',
    callingCode: '225',
  },
  {
    name: 'Jamaica',
    callingCode: '1876',
  },
  {
    name: 'Japan',
    callingCode: '81',
  },
  {
    name: 'Jordan',
    callingCode: '962',
  },
  {
    name: 'Kazakhstan',
    callingCode: '7',
  },
  {
    name: 'Kenya',
    callingCode: '254',
  },
  {
    name: 'Kiribati',
    callingCode: '686',
  },
  {
    name: 'Kuwait',
    callingCode: '965',
  },
  {
    name: 'Kyrgyzstan',
    callingCode: '996',
  },
  {
    name: 'Laos',
    callingCode: '856',
  },
  {
    name: 'Latvia',
    callingCode: '371',
  },
  {
    name: 'Lebanon',
    callingCode: '961',
  },
  {
    name: 'Lesotho',
    callingCode: '266',
  },
  {
    name: 'Liberia',
    callingCode: '231',
  },
  {
    name: 'Libyan Arab Jamahiriya',
    callingCode: '218',
  },
  {
    name: 'Liechtenstein',
    callingCode: '423',
  },
  {
    name: 'Lithuania',
    callingCode: '370',
  },
  {
    name: 'Luxembourg',
    callingCode: '352',
  },
  {
    name: 'Macao',
    callingCode: '853',
  },
  {
    name: 'North Macedonia',
    callingCode: '389',
  },
  {
    name: 'Madagascar',
    callingCode: '261',
  },
  {
    name: 'Malawi',
    callingCode: '265',
  },
  {
    name: 'Malaysia',
    callingCode: '60',
  },
  {
    name: 'Maldives',
    callingCode: '960',
  },
  {
    name: 'Mali',
    callingCode: '223',
  },
  {
    name: 'Malta',
    callingCode: '356',
  },
  {
    name: 'Marshall Islands',
    callingCode: '692',
  },
  {
    name: 'Martinique',
    callingCode: '596',
  },
  {
    name: 'Mauritania',
    callingCode: '222',
  },
  {
    name: 'Mauritius',
    callingCode: '230',
  },
  {
    name: 'Mayotte',
    callingCode: '262',
  },
  {
    name: 'Mexico',
    callingCode: '52',
  },
  {
    name: 'Micronesia, Federated States of',
    callingCode: '691',
  },
  {
    name: 'Moldova',
    callingCode: '373',
  },
  {
    name: 'Monaco',
    callingCode: '377',
  },
  {
    name: 'Mongolia',
    callingCode: '976',
  },
  {
    name: 'Montserrat',
    callingCode: '1664',
  },
  {
    name: 'Morocco',
    callingCode: '212',
  },
  {
    name: 'Mozambique',
    callingCode: '258',
  },
  {
    name: 'Myanmar',
    callingCode: '95',
  },
  {
    name: 'Namibia',
    callingCode: '264',
  },
  {
    name: 'Nauru',
    callingCode: '674',
  },
  {
    name: 'Nepal',
    callingCode: '977',
  },
  {
    name: 'Netherlands',
    callingCode: '31',
  },
  {
    name: 'Netherlands Antilles',
    callingCode: '599',
  },
  {
    name: 'New Caledonia',
    callingCode: '687',
  },
  {
    name: 'New Zealand',
    callingCode: '64',
  },
  {
    name: 'Nicaragua',
    callingCode: '505',
  },
  {
    name: 'Niger',
    callingCode: '227',
  },
  {
    name: 'Nigeria',
    callingCode: '234',
  },
  {
    name: 'Niue',
    callingCode: '683',
  },
  {
    name: 'Norfolk Island',
    callingCode: '672',
  },
  {
    name: 'North Korea',
    callingCode: '850',
  },
  {
    name: 'Northern Ireland',
    callingCode: '44',
  },
  {
    name: 'Northern Mariana Islands',
    callingCode: '1670',
  },
  {
    name: 'Norway',
    callingCode: '47',
  },
  {
    name: 'Oman',
    callingCode: '968',
  },
  {
    name: 'Pakistan',
    callingCode: '92',
  },
  {
    name: 'Palau',
    callingCode: '680',
  },
  {
    name: 'Palestine',
    callingCode: '970',
  },
  {
    name: 'Panama',
    callingCode: '507',
  },
  {
    name: 'Papua New Guinea',
    callingCode: '675',
  },
  {
    name: 'Paraguay',
    callingCode: '595',
  },
  {
    name: 'Peru',
    callingCode: '51',
  },
  {
    name: 'Philippines',
    callingCode: '63',
  },
  {
    name: 'Pitcairn',
    callingCode: '64',
  },
  {
    name: 'Poland',
    callingCode: '48',
  },
  {
    name: 'Portugal',
    callingCode: '351',
  },
  {
    name: 'Puerto Rico',
    callingCode: '1939',
  },
  {
    name: 'Qatar',
    callingCode: '974',
  },
  {
    name: 'Reunion',
    callingCode: '262',
  },
  {
    name: 'Romania',
    callingCode: '40',
  },
  {
    name: 'Russian Federation',
    callingCode: '7',
  },
  {
    name: 'Rwanda',
    callingCode: '250',
  },
  {
    name: 'Saint Helena',
    callingCode: '290',
  },
  {
    name: 'Saint Kitts and Nevis',
    callingCode: '1869',
  },
  {
    name: 'Saint Lucia',
    callingCode: '1758',
  },
  {
    name: 'Saint Pierre and Miquelon',
    callingCode: '508',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    callingCode: '1784',
  },
  {
    name: 'Samoa',
    callingCode: '685',
  },
  {
    name: 'San Marino',
    callingCode: '378',
  },
  {
    name: 'Sao Tome and Principe',
    callingCode: '239',
  },
  {
    name: 'Saudi Arabia',
    callingCode: '966',
  },
  {
    name: 'Scotland',
    callingCode: '44',
  },
  {
    name: 'Senegal',
    callingCode: '221',
  },
  {
    name: 'Seychelles',
    callingCode: '248',
  },
  {
    name: 'Sierra Leone',
    callingCode: '232',
  },
  {
    name: 'Singapore',
    callingCode: '65',
  },
  {
    name: 'Slovakia',
    callingCode: '421',
  },
  {
    name: 'Slovenia',
    callingCode: '386',
  },
  {
    name: 'Solomon Islands',
    callingCode: '677',
  },
  {
    name: 'Somalia',
    callingCode: '252',
  },
  {
    name: 'South Africa',
    callingCode: '27',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    callingCode: '500',
  },
  {
    name: 'South Korea',
    callingCode: '82',
  },
  {
    name: 'South Sudan',
    callingCode: '211',
  },
  {
    name: 'Spain',
    callingCode: '34',
  },
  {
    name: 'SriLanka',
    callingCode: '94',
  },
  {
    name: 'Sudan',
    callingCode: '249',
  },
  {
    name: 'Suriname',
    callingCode: '597',
  },
  {
    name: 'Svalbard and Jan Mayen',
    callingCode: '47',
  },
  {
    name: 'Swaziland',
    callingCode: '268',
  },
  {
    name: 'Sweden',
    callingCode: '46',
  },
  {
    name: 'Switzerland',
    callingCode: '41',
  },
  {
    name: 'Syria',
    callingCode: '963',
  },
  {
    name: 'Tajikistan',
    callingCode: '992',
  },
  {
    name: 'Tanzania',
    callingCode: '255',
  },
  {
    name: 'Thailand',
    callingCode: '66',
  },
  {
    name: 'The Democratic Republic of Congo',
    callingCode: '243',
  },
  {
    name: 'Togo',
    callingCode: '228',
  },
  {
    name: 'Tokelau',
    callingCode: '690',
  },
  {
    name: 'Tonga',
    callingCode: '676',
  },
  {
    name: 'Trinidad and Tobago',
    callingCode: '1868',
  },
  {
    name: 'Tunisia',
    callingCode: '216',
  },
  {
    name: 'Turkey',
    callingCode: '90',
  },
  {
    name: 'Turkmenistan',
    callingCode: '993',
  },
  {
    name: 'Turks and Caicos Islands',
    callingCode: '1649',
  },
  {
    name: 'Tuvalu',
    callingCode: '688',
  },
  {
    name: 'Uganda',
    callingCode: '256',
  },
  {
    name: 'Ukraine',
    callingCode: '380',
  },
  {
    name: 'United Arab Emirates',
    callingCode: '971',
  },
  {
    name: 'United Kingdom',
    callingCode: '44',
  },
  {
    name: 'United States',
    callingCode: '1',
  },
  {
    name: 'United States Minor Outlying Islands',
    callingCode: '246',
  },
  {
    name: 'Uruguay',
    callingCode: '598',
  },
  {
    name: 'Uzbekistan',
    callingCode: '998',
  },
  {
    name: 'Vanuatu',
    callingCode: '678',
  },
  {
    name: 'Venezuela',
    callingCode: '58',
  },
  {
    name: 'Vietnam',
    callingCode: '84',
  },
  {
    name: 'Virgin Islands, British',
    callingCode: '1284',
  },
  {
    name: 'Virgin Islands, U.S.',
    callingCode: 1,
  },
  {
    name: 'Wales',
    callingCode: '44',
  },
  {
    name: 'Wallis and Futuna',
    callingCode: '681',
  },
  {
    name: 'Western Sahara',
    callingCode: '212',
  },
  {
    name: 'Yemen',
    callingCode: '967',
  },
  {
    name: 'Yugoslavia',
    callingCode: '38',
  },
  {
    name: 'Zambia',
    callingCode: '260',
  },
  {
    name: 'Zimbabwe',
    callingCode: '263',
  },
];

// http://country.io/names.json
export const countryCodeNames = {
  BD: 'Bangladesh',
  BE: 'Belgium',
  BF: 'Burkina Faso',
  BG: 'Bulgaria',
  BA: 'Bosnia and Herzegovina',
  BB: 'Barbados',
  WF: 'Wallis and Futuna',
  BL: 'Saint Barthelemy',
  BM: 'Bermuda',
  BN: 'Brunei',
  BO: 'Bolivia',
  BH: 'Bahrain',
  BI: 'Burundi',
  BJ: 'Benin',
  BT: 'Bhutan',
  JM: 'Jamaica',
  BV: 'Bouvet Island',
  BW: 'Botswana',
  WS: 'Samoa',
  BQ: 'Bonaire, Saint Eustatius and Saba ',
  BR: 'Brazil',
  BS: 'Bahamas',
  JE: 'Jersey',
  BY: 'Belarus',
  BZ: 'Belize',
  RU: 'Russia',
  RW: 'Rwanda',
  RS: 'Serbia',
  TL: 'East Timor',
  RE: 'Reunion',
  TM: 'Turkmenistan',
  TJ: 'Tajikistan',
  RO: 'Romania',
  TK: 'Tokelau',
  GW: 'Guinea-Bissau',
  GU: 'Guam',
  GT: 'Guatemala',
  GS: 'South Georgia and the South Sandwich Islands',
  GR: 'Greece',
  GQ: 'Equatorial Guinea',
  GP: 'Guadeloupe',
  JP: 'Japan',
  GY: 'Guyana',
  GG: 'Guernsey',
  GF: 'French Guiana',
  GE: 'Georgia',
  GD: 'Grenada',
  GB: 'United Kingdom',
  GA: 'Gabon',
  SV: 'El Salvador',
  GN: 'Guinea',
  GM: 'Gambia',
  GL: 'Greenland',
  GI: 'Gibraltar',
  GH: 'Ghana',
  OM: 'Oman',
  TN: 'Tunisia',
  JO: 'Jordan',
  HR: 'Croatia',
  HT: 'Haiti',
  HU: 'Hungary',
  HK: 'Hong Kong',
  HN: 'Honduras',
  HM: 'Heard Island and McDonald Islands',
  VE: 'Venezuela',
  PR: 'Puerto Rico',
  PS: 'Palestinian Territory',
  PW: 'Palau',
  PT: 'Portugal',
  SJ: 'Svalbard and Jan Mayen',
  PY: 'Paraguay',
  IQ: 'Iraq',
  PA: 'Panama',
  PF: 'French Polynesia',
  PG: 'Papua New Guinea',
  PE: 'Peru',
  PK: 'Pakistan',
  PH: 'Philippines',
  PN: 'Pitcairn',
  PL: 'Poland',
  PM: 'Saint Pierre and Miquelon',
  ZM: 'Zambia',
  EH: 'Western Sahara',
  EE: 'Estonia',
  EG: 'Egypt',
  ZA: 'South Africa',
  EC: 'Ecuador',
  IT: 'Italy',
  VN: 'Vietnam',
  SB: 'Solomon Islands',
  ET: 'Ethiopia',
  SO: 'Somalia',
  ZW: 'Zimbabwe',
  SA: 'Saudi Arabia',
  ES: 'Spain',
  ER: 'Eritrea',
  ME: 'Montenegro',
  MD: 'Moldova',
  MG: 'Madagascar',
  MF: 'Saint Martin',
  MA: 'Morocco',
  MC: 'Monaco',
  UZ: 'Uzbekistan',
  MM: 'Myanmar',
  ML: 'Mali',
  MO: 'Macao',
  MN: 'Mongolia',
  MH: 'Marshall Islands',
  MK: 'Macedonia',
  MU: 'Mauritius',
  MT: 'Malta',
  MW: 'Malawi',
  MV: 'Maldives',
  MQ: 'Martinique',
  MP: 'Northern Mariana Islands',
  MS: 'Montserrat',
  MR: 'Mauritania',
  IM: 'Isle of Man',
  UG: 'Uganda',
  TZ: 'Tanzania',
  MY: 'Malaysia',
  MX: 'Mexico',
  IL: 'Israel',
  FR: 'France',
  IO: 'British Indian Ocean Territory',
  SH: 'Saint Helena',
  FI: 'Finland',
  FJ: 'Fiji',
  FK: 'Falkland Islands',
  FM: 'Micronesia',
  FO: 'Faroe Islands',
  NI: 'Nicaragua',
  NL: 'Netherlands',
  NO: 'Norway',
  NA: 'Namibia',
  VU: 'Vanuatu',
  NC: 'New Caledonia',
  NE: 'Niger',
  NF: 'Norfolk Island',
  NG: 'Nigeria',
  NZ: 'New Zealand',
  NP: 'Nepal',
  NR: 'Nauru',
  NU: 'Niue',
  CK: 'Cook Islands',
  XK: 'Kosovo',
  CI: 'Ivory Coast',
  CH: 'Switzerland',
  CO: 'Colombia',
  CN: 'China',
  CM: 'Cameroon',
  CL: 'Chile',
  CC: 'Cocos Islands',
  CA: 'Canada',
  CG: 'Republic of the Congo',
  CF: 'Central African Republic',
  CD: 'Democratic Republic of the Congo',
  CZ: 'Czech Republic',
  CY: 'Cyprus',
  CX: 'Christmas Island',
  CR: 'Costa Rica',
  CW: 'Curacao',
  CV: 'Cape Verde',
  CU: 'Cuba',
  SZ: 'Swaziland',
  SY: 'Syria',
  SX: 'Sint Maarten',
  KG: 'Kyrgyzstan',
  KE: 'Kenya',
  SS: 'South Sudan',
  SR: 'Suriname',
  KI: 'Kiribati',
  KH: 'Cambodia',
  KN: 'Saint Kitts and Nevis',
  KM: 'Comoros',
  ST: 'Sao Tome and Principe',
  SK: 'Slovakia',
  KR: 'South Korea',
  SI: 'Slovenia',
  KP: 'North Korea',
  KW: 'Kuwait',
  SN: 'Senegal',
  SM: 'San Marino',
  SL: 'Sierra Leone',
  SC: 'Seychelles',
  KZ: 'Kazakhstan',
  KY: 'Cayman Islands',
  SG: 'Singapore',
  SE: 'Sweden',
  SD: 'Sudan',
  DO: 'Dominican Republic',
  DM: 'Dominica',
  DJ: 'Djibouti',
  DK: 'Denmark',
  VG: 'British Virgin Islands',
  DE: 'Germany',
  YE: 'Yemen',
  DZ: 'Algeria',
  US: 'United States',
  UY: 'Uruguay',
  YT: 'Mayotte',
  UM: 'United States Minor Outlying Islands',
  LB: 'Lebanon',
  LC: 'Saint Lucia',
  LA: 'Laos',
  TV: 'Tuvalu',
  TW: 'Taiwan',
  TT: 'Trinidad and Tobago',
  TR: 'Turkey',
  LK: 'Sri Lanka',
  LI: 'Liechtenstein',
  LV: 'Latvia',
  TO: 'Tonga',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LR: 'Liberia',
  LS: 'Lesotho',
  TH: 'Thailand',
  TF: 'French Southern Territories',
  TG: 'Togo',
  TD: 'Chad',
  TC: 'Turks and Caicos Islands',
  LY: 'Libya',
  VA: 'Vatican',
  VC: 'Saint Vincent and the Grenadines',
  AE: 'United Arab Emirates',
  AD: 'Andorra',
  AG: 'Antigua and Barbuda',
  AF: 'Afghanistan',
  AI: 'Anguilla',
  VI: 'U.S. Virgin Islands',
  IS: 'Iceland',
  IR: 'Iran',
  AM: 'Armenia',
  AL: 'Albania',
  AO: 'Angola',
  AQ: 'Antarctica',
  AS: 'American Samoa',
  AR: 'Argentina',
  AU: 'Australia',
  AT: 'Austria',
  AW: 'Aruba',
  IN: 'India',
  AX: 'Aland Islands',
  AZ: 'Azerbaijan',
  IE: 'Ireland',
  ID: 'Indonesia',
  UA: 'Ukraine',
  QA: 'Qatar',
  MZ: 'Mozambique',
};
